---

- name: Create automation directory
  file:
    path: /opt/automation
    state: directory
    owner: root
    group: root
    recurse: true

- include_tasks: serf.yml
  tags: [serf, services]

# - include_tasks: netdata.yml
#   tags: [netdata, services]

- when:
  - raid_groups is not none
  - raid_groups | length > 0
  include_tasks: raid.yml
  tags: [raid, storage]
  loop: "{{ raid_groups }}"
  args:
    apply:
      vars:
        raid_name: "{{ item.name }}"
        raid_level: "{{ item.level|default(1) }}"
        raid_devices: "{{ item.devices }}"
        volume_group: "{{ item.volume_group }}"
        logical_volume: "{{ item.logical_volume }}"
        mount_point: "{{ item.mount_point }}"
        fs_type: "{{ item.fs_type|default('ext4') }}"
        run_anyway: "{{ item.yes_i_know_what_im_doing|default(false) }}"

- include_tasks: mailer.yml
  tags: [mailer, services]
