---

- name: Create automation directory
  ansible.builtin.file:
    path: /opt/automation
    state: directory
    owner: root
    group: root
    recurse: true

- ansible.builtin.include_tasks: serf.yml
  args:
    apply:
      vars:
        _serf_state: "{{ serf_state|default('absent') }}"
  tags: [serf, services]

- when:
  - raid_groups is not none
  - raid_groups | length > 0
  ansible.builtin.include_tasks: raid.yml
  tags: [raid, storage]
  loop: "{{ raid_groups }}"
  args:
    apply:
      vars:
        raid_name: "{{ item.name }}"
        raid_level: "{{ item.level|default(1) }}"
        raid_devices: "{{ item.devices }}"
        volume_group: "{{ item.volume_group }}"
        logical_volume: "{{ item.logical_volume }}"
        mount_point: "{{ item.mount_point }}"
        fs_type: "{{ item.fs_type|default('ext4') }}"
        run_anyway: "{{ item.yes_i_know_what_im_doing|default(false) }}"

- ansible.builtin.include_tasks: mailer.yml
  tags: [mailer, services]

- ansible.builtin.include_tasks: sshguard.yml
  tags: [sshguard, services]

- ansible.builtin.include_role:
    name: singleplatform-eng.users
