---

networks:
  backend: {}
  
x-service-common: &service-common
  pull_policy: "always"
  restart: "unless-stopped"
  env_file: "{{ minio_stack_dir }}/env"
  networks:
  - "backend"

services:
  minio:
    <<: *service-common
    image: "docker.io/minio/minio:latest"
    command:
    - "server"
    - "--json"
    - "/disks/disk1"
    - "/disks/disk2"
    - "/disks/disk3"
    volumes:
    - "{{ minio_disks_dir }}:/disks"

  traefik:
    <<: *service-common
    image: "docker.io/library/traefik:3"
    volumes:
    - "{{ minio_stack_dir }}/traefik/traefik.yml:/config/traefik.yml:ro"
    - "{{ minio_stack_dir }}/traefik/conf.d:/config/conf.d:ro"
    - "{{ minio_stack_dir }}/traefik/data/acme:/acme"
    ports:
    - "80:80"
    - "443:443"
    - "8889:8889"
    - "8891:8891"
    command:
    - "--configfile=/config/traefik.yml"

  vector:
    <<: *service-common
    image: docker.io/timberio/vector:nightly-distroless-static
    command:
      - -c
      - /config/vector.toml
    ports:
      - 6000:6000 # source: vector-receiver
      - 8686:8686 # api
    volumes:
      - "{{ minio_stack_dir }}/vector/conf:/config"
      - "{{ minio_stack_dir }}/vector/data:/data"
      - "/:/host:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
