auth_enabled: false

server:
  log_level: info
  log_format: json
  http_listen_port: {{ env "NOMAD_PORT_http" }}
  grpc_listen_port: {{ env "NOMAD_PORT_grpc" }}
  register_instrumentation: true

common:
  path_prefix: {{ env "NOMAD_ALLOC_DIR" }}
  replication_factor: 1
  # Tell Loki which address to advertise
  instance_addr: {{ env "NOMAD_IP_grpc" }}
  ring:
    # Tell Loki which address to advertise in ring
    instance_addr: {{ env "NOMAD_IP_grpc" }}
    kvstore:
      store: inmemory

ingester:
  wal:
    dir: {{ env "NOMAD_ALLOC_DIR" }}/data/wal
    flush_on_shutdown: true
    replay_memory_ceiling: "1G"

schema_config:
  configs:
  - from: 2022-05-15
    store: boltdb-shipper
    object_store: s3
    schema: v12
    index:
      prefix: index_
      period: 24h
  - from: 2024-04-17
    object_store: s3
    store: tsdb
    schema: v13
    index:
      prefix: index_
      period: 24h

storage_config:
  boltdb_shipper:
    # Nomad ephemeral disk is used to store index and cache
    # it will try to preserve /alloc/data between job updates
    active_index_directory: {{ env "NOMAD_ALLOC_DIR" }}/data/index
    cache_location: {{ env "NOMAD_ALLOC_DIR" }}/data/index-cache

  aws:
    endpoint: ${S3_ENDPOINT_URL}
    bucketnames: ${S3_BUCKET_NAME}
    region: ${S3_REGION}
    access_key_id: ${S3_ACCESS_KEY_ID}
    secret_access_key: ${S3_SECRET_ACCESS_KEY}
    s3forcepathstyle: true
    insecure: ${S3_INSECURE}

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  retention_period: 4464h
  allow_structured_metadata: true
  discover_service_name:
  - appname
  - job
  - application

compactor:
  working_directory: {{ env "NOMAD_ALLOC_DIR" }}/compactor
  compaction_interval: 5m
  delete_request_store: s3
  retention_enabled: true

ruler:
  alertmanager_url: https://alertmanager.${DOMAIN}
  enable_alertmanager_v2: true
  enable_api: true
  external_url: https://loki.${DOMAIN}
  rule_path: {{ env "NOMAD_ALLOC_DIR" }}/tmp/rules
  storage:
    type: local
    local:
      directory: {{ env "NOMAD_TASK_DIR" }}/rules
  wal:
    dir: {{ env "NOMAD_ALLOC_DIR" }}/data/ruler