---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nvidia-k8s-device-plugin-repo
  namespace: flux-system
spec:
  interval: 1h0m0s
  type: default
  url: https://nvidia.github.io/k8s-device-plugin
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nvidia-k8s-device-plugin
  namespace: flux-system
spec:
  chart:
    spec:
      chart: nvidia-device-plugin
      sourceRef:
        kind: HelmRepository
        name: nvidia-k8s-device-plugin-repo
  interval: 1h0m0s
  targetNamespace: kube-system
  install:
    createNamespace: false
    values: {}