---
- name: Make stack directory
  ansible.builtin.file:
    path: "{{ compose_stack_dir }}"
    state: "directory"
    owner: "root"
    group: "root"
    recurse: yes

- name: Sync stack to remote
  ansible.posix.synchronize:
    src: "compose/"
    dest: "{{ compose_stack_dir }}"
    mode: "push"
    recursive: yes

- name: Template env file
  ansible.builtin.template:
    src: "files/env.j2"
    dest: "{{ compose_stack_dir }}/.env"
    owner: "root"
    group: "root"
    mode: "0640"

- name: Compose deployment
  community.docker.docker_compose_v2:
    project_src: "{{ compose_stack_dir }}"
    pull: always
    state: "{{ periphery_state }}"
  when:
    - periphery_docker_mode == "compose"

- name: Stack deployment
  community.docker.docker_stack:
    name: "komodo"
    compose:
      - "{{ compose_stack_dir }}/stack.yml"
    detach: false
    state: "{{ periphery_state }}"
  when:
    - periphery_docker_mode == "swarm"
  register: stack_deployment
  environment:
    STACK_DIR: "{{ compose_stack_dir }}"
    PERIPHERY_VERSION: "{{ periphery_version }}"
    PERIPHERY_ROOT_DIRECTORY: "{{ compose_data_dir }}"
  failed_when: '"rolling back" in stack_deployment.stdout'

- name: Output stack deployment warnings
  debug:
    msg: |
      Docker stack deploy emitted some warnings:
      {% for line in stack_deployment.stderr_lines %}
      {%- if line.strip() != "" %}
        - {{ line }}
      {% endif %}{% endfor %}
  when:
    - stack_deployment.stderr.strip() != ""
