####################################
# 🦎 KOMODO COMPOSE - PERIPHERY 🦎 #
####################################

## This compose file will deploy:
##   1. Komodo Periphery

x-deploy: &deploy
  mode: global
  restart_policy:
    condition: any
    delay: 15s
  rollback_config:
    parallelism: 0
    failure_action: pause
    monitor: 15s
    order: stop-first
  update_config:
    parallelism: 1
    failure_action: rollback
    monitor: 15s
    order: stop-first

services:
  periphery:
    image: ghcr.io/moghtech/komodo-periphery:${PERIPHERY_VERSION}
    labels:
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers
    env_file: .env
    ## https://komo.do/docs/connect-servers#configuration
    volumes:
      ## Mount external docker socket
      - /var/run/docker.sock:/var/run/docker.sock
      ## Allow Periphery to see processes outside of container
      - /proc:/proc
      ## Specify the Periphery agent root directory.
      ## Must be the same inside and outside the container,
      ## or docker will get confused. See https://github.com/moghtech/komodo/discussions/180.
      ## Default: /etc/komodo.
      - ${PERIPHERY_ROOT_DIRECTORY}:${PERIPHERY_ROOT_DIRECTORY}
    ## If periphery is being run remote from the core server, ports need to be exposed
    ports:
      - target: 8120
        published: 8120
        protocol: tcp
        mode: host
    ## If you want to use a custom periphery config file, use command to pass it to periphery.
    # command: periphery --config-path ${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}/periphery.config.toml
    deploy:
      <<: *deploy

  vector:
    image: docker.io/timberio/vector:nightly-distroless-static
    restart: unless-stopped
    command:
      - -c
      - /config/vector.toml
    ports:
      - target: 6000
        published: 6000
        protocol: tcp
      - target: 8686
        published: 8686
        protocol: tcp
        mode: host
    volumes:
      - "${STACK_DIR}/vector:/config"
      - "${STACK_DIR}/vector/data:/data"
      - "/:/host:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      <<: *deploy
