---

k3s_mode: ~

postgres_version: 15.3-alpine
postgres_root_password: ~
postgres_k3s_user: k3s
postgres_k3s_password: ~
postgres_k3s_database: k3s

pgadmin_image: "dpage/pgadmin4"
pgadmin_version: 6
pgadmin_default_email: ~
pgadmin_default_password: ~

nginx_proxy_manager_image: jc21/nginx-proxy-manager
nginx_proxy_manager_version: latest
