---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nvidia-k8s
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./fluxcd/apps/main/nvidia-k8s
  prune: true
  sourceRef:
    kind: GitRepository
    name: pve-automation

