---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./fluxcd/apps/main/longhorn
  prune: true
  sourceRef:
    kind: GitRepository
    name: pve-automation

