---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pve-automation-secrets
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  interval: 10m0s
  path: ./fluxcd/clusters/main/secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: pve-automation
