---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: weave-scope
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./fluxcd/apps/main/weave-scope
  prune: true
  sourceRef:
    kind: GitRepository
    name: pve-automation

