---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: postgres-operator-charts
  namespace: flux-system
spec:
  interval: 1h0m0s
  type: default
  url: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: postgres-operator-ui-charts
  namespace: flux-system
spec:
  interval: 1h0m0s
  type: default
  url: https://opensource.zalando.com/postgres-operator/charts/postgres-operator-ui
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres-operator
  namespace: flux-system
spec:
  chart:
    spec:
      chart: postgres-operator
      sourceRef:
        kind: HelmRepository
        name: postgres-operator-charts
  interval: 1h0m0s
  targetNamespace: postgres-operator
  install:
    createNamespace: true
  values: {}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres-operator-ui
  namespace: flux-system
spec:
  chart:
    spec:
      chart: postgres-operator-ui
      sourceRef:
        kind: HelmRepository
        name: postgres-operator-ui-charts
  interval: 1h0m0s
  targetNamespace: postgres-operator
  install:
    createNamespace: true
  values: {}