---
- name: Apt repo update
  ansible.builtin.apt:
    update_cache: yes

- name: Restart docker
  ansible.builtin.service:
    name: docker
    state: restarted

- name: Restart k3s
  ansible.builtin.service:
    name: k3s
    state: restarted
  when: k3s_control_node is defined

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
