---

- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
  - linux-modules-extra-{{ ansible_kernel }}
  - nfs-common
  - open-iscsi
  - xfsprogs

- name: Load extra modules
  modprobe:
    name: "{{ item }}"
    state: present
    persistent: present
  loop:
  - uio
  - uio_pci_generic
  - iscsi_tcp
  notify:
  - Restart k3s

- name: Start/enable iSCSI service
  systemd:
    name: iscsid
    state: started
    enabled: true
  notify:
  - Restart k3s