---

- include_tasks: support.yml
  when: k3s_mode == "support"

- include_tasks: disks.yml
  when:
  - k3s_mode != "support"
  - k3s_longhorn_data_disks is defined
  - k3s_longhorn_volume_directory is defined
  tags: [disks]

- include_tasks: extras.yml
  when: k3s_mode != "support"
  tags: [extras]

- include_tasks: gpu.yml
  when: k3s_worker_pool|default('none') == "gpu"
  tags: [gpu]