---

- name: Reload systemd
  systemd:
    daemon_reload: yes
  when: packer_build_type is not defined

- name: Reload serf
  systemd:
    name: serf.service
    state: reloaded
  when: packer_build_type is not defined

- name: Restart netdata service
  systemd:
    name: netdata.service
    state: restarted
  when:
  - packer_build_type is not defined
  - netdata_start_after_install