---

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Restart nomad
  include_tasks:
    file: ./restart_nomad.yml
  when: nomad_allow_automatic_restart is truthy

- name: Reload nomad
  systemd:
    name: nomad
    state: reloaded

- name: Enable nomad service
  systemd:
    name: nomad
    enabled: yes

- name: Restart multipath-tools
  systemd:
    name: multipath-tools
    state: restarted
