---

- name: Get GOPATH
  command: "go env GOPATH"
  changed_when: false
  register: GOPATH

- name: Stop serf
  systemd:
    name: serf.service
    enabled: no
    state: stopped

- name: Remove packages
  apt:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
      - golang-go

- name: Remove installed artifacts
  file:
    name: "{{ GOPATH.stdout }}"
    state: absent
  loop:
    - "{{ GOPATH.stdout }}"
    - "/usr/local/bin/serf"
    - "/etc/systemd/system/serf.service"
    - "/etc/serf"
    - "/opt/serf/handlers"
