---

- name: Get GOPATH
  command: "go env GOPATH"
  changed_when: false
  register: GOPATH

- name: Stop serf
  systemd:
    name: serf.service
    enabled: no
    state: stopped
  failed_when: false

- name: Remove installed artifacts
  file:
    name: "{{ item }}"
    state: absent
  loop:
    - "/usr/local/bin/serf"
    - "/etc/systemd/system/serf.service"
    - "/etc/serf"
    - "/opt/serf/handlers"
  failed_when: false
