---

- hosts: localhost
  tags: [always]
  tasks:
  - name: Read Terraform outputs
    set_fact:
      _terraform_outputs: "{{ lookup('cloud.terraform.tf_output', binary_path=tf_binary, project_path=tf_project_path) }}"
      tf_project_path: "{{ tf_project_path }}"
    vars:
      tf_binary: "{{ 'tofu'|which }}"
      tf_project_path: "{{ (playbook_dir, '..', 'terraform', 'nomad-main', 'infra')|path_join }}"

  - name: Add minio server nodes
    add_host:
      name: "{{ item['name'] }}"
      groups: [minio_server]
      ansible_host: "{{ item['ip'] }}"
      ansible_user: "{{ item['user'] }}"
      ansible_python_interpreter: /usr/bin/python3
      tf_project_path: "{{ tf_project_path }}"
      tf_state_outputs: "{{ _terraform_outputs }}"
      attributes: "{{ item['attributes'] }}"
    loop: "{{ _terraform_outputs['minio_server_inventory']['value'] }}"
    changed_when: false

- ansible.builtin.import_playbook: "play-base.yml"
  tags: [base]
  vars:
    base_tailscale_up_skip: false

- hosts: "{{ limit | default('minio_server') }}"
  become: true
  roles:
  - role: docker
    tags: [docker]
  - role: minio
    tags: [minio]
