---
- hosts: localhost
  tags: [always]
  tasks:
    - name: Load terraform outputs
      ansible.builtin.include_tasks: tasks/load-hosts.yml
      vars:
        infra_project: "rrtnet-infra"

    - name: Add minio server nodes
      add_host:
        name: "{{ item['name'] }}"
        groups: [minio_server]
        ansible_host: "{{ item['ip'] }}"
        ansible_user: "{{ item['user'] }}"
        ansible_python_interpreter: /usr/bin/python3
        tf_project_path: "{{ tf_project_path }}"
        tf_state_outputs: "{{ _terraform_outputs }}"
        attributes: "{{ item['attributes'] }}"
      loop: "{{ _terraform_outputs['minio_server_inventory']['value'] }}"
      changed_when: false

- ansible.builtin.import_playbook: "play-base.yml"
  tags: [base]
  vars:
    base_tailscale_up_skip: false
    _target: "{{ target|default('minio_server') }}"

- hosts: "{{ target|default('minio_server') }}"
  become: true
  roles:
    - role: geerlingguy.docker
      tags: [base, docker]
    - role: docker
      tags: [docker]
    - role: minio
      tags: [minio]
