---

http:
  routers:
    minio-console:
      priority: 100
      rule: "Host(`console.s3.{{ minio_base_domain }}`)"
      entrypoints:
      - "web-secure"
      service: "minio-console"
      tls:
        certResolver: "letsencrypt_prod"
        domains:
        - main: "s3.{{ minio_base_domain }}"
          sans:
          - "*.s3.{{ minio_base_domain }}"
    minio-api:
      priority: 50
      rule: "Host(`s3.{{ minio_base_domain }}`) || HostRegexp(`^.+\\.s3\\.{{ minio_base_domain }}$`)"
      entrypoints:
      - "web-secure"
      - "cftunnel-secure"
      service: "minio-api"
      tls:
        certResolver: "letsencrypt_prod"
        domains:
        - main: "s3.{{ minio_base_domain }}"
          sans:
          - "*.s3.{{ minio_base_domain }}"

  services:
    minio-console:
      loadBalancer:
        servers:
        - url: "http://minio:9001"
        passHostHeader: true
    minio-api:
      loadBalancer:
        servers:
        - url: "http://minio:9000"
        passHostHeader: true
