---

http:
  routers:
    minio-console:
      rule: "Host(`console.s3.2811rrt.net`)"
      entrypoints:
      - "web-secure"
      service: "minio-console"
      tls:
        certResolver: "letsencrypt_prod"
        domains:
        - main: "s3.2811rrt.net"
          sans:
          - "*.s3.2811rrt.net"
    minio-api:
      rule: "Host(`s3.2811rrt.net`) || HostRegexp(`^.+\\.s3\\.2811rrt\\.net$`)"
      entrypoints:
      - "web-secure"
      service: "minio-api"
      tls:
        certResolver: "letsencrypt_prod"
        domains:
        - main: "s3.2811rrt.net"
          sans:
          - "*.s3.2811rrt.net"

  services:
    minio-console:
      loadBalancer:
        servers:
        - url: "http://minio:9001"
        passHostHeader: true
    minio-api:
      loadBalancer:
        servers:
        - url: "http://minio:9000"
        passHostHeader: true
