---
- name: Make stack directory
  ansible.builtin.file:
    path: "{{ periphery_stack_dir }}"
    state: "directory"
    owner: "root"
    group: "root"
    recurse: yes
    
- name: Docker compose deployment
  ansible.builtin.include_tasks: docker/compose.yml
  when:
    - periphery_docker_mode == "compose"

- name: Docker swarm stack deployment
  ansible.builtin.include_tasks: docker/swarm.yml
  when:
    - periphery_docker_mode == "swarm"