---

- name: Format disks
  community.general.filesystem:
    dev: "{{ item }}"
    fstype: "xfs"
    resizefs: yes
    state: "present"
  loop:
  - /dev/vdb
  - /dev/vdc
  - /dev/vdd

- name: Make mountpoint
  ansible.builtin.file:
    path: "/disks"
    state: "directory"
    owner: "root"
    group: "root"

- name: Mount disks
  ansible.posix.mount:
    path: "{{ item.dest }}"
    src: "{{ item.src }}"
    fstype: "xfs"
    boot: yes
    state: "mounted"
  loop:
  - {src: /dev/vdb, dest: /disks/disk1}
  - {src: /dev/vdc, dest: /disks/disk2}
  - {src: /dev/vdd, dest: /disks/disk3}

- name: Make stack directory
  ansible.builtin.file:
    path: "/opt/stacks/minio"
    state: "directory"
    owner: "root"
    group: "root"
    recurse: yes

- name: Sync stack to remote
  ansible.posix.synchronize:
    src: "compose/"
    dest: "/opt/stacks/minio/"
    mode: "push"
    recursive: yes

- name: Template env file
  ansible.builtin.template:
    src: "files/env.j2"
    dest: "/opt/stacks/minio/env"
    owner: "root"
    group: "root"
    mode: "0640"

- name: Deployment
  community.docker.docker_compose_v2:
    project_src: "/opt/stacks/minio"
    state: "present"