---

- name: Restart nginx
  community.docker.docker_container:
    name: k3s-nginx
    restart: true

- name: Restart k3s
  systemd:
    name: k3s
    state: restarted
  when: ansible_facts.services.get("k3s", {}).get("state", "unknown") != "unknown"

- name: Restart docker
  systemd:
    name: docker
    state: restarted

- name: Restart containerd
  systemd:
    name: containerd
    state: restarted

- name: Apt repo update
  apt:
    update_cache: yes
    cache_valid_time: 3600